#!/usr/bin/env bash
# configuration of ufw firewall to block incoming 
# traffic except tcp port 22, 80 and 443

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose 
